version: "3"
services:
  stock_es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: stock_es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - stock_es_data:/usr/share/elasticsearch/data

volumes:
  stock_es_data:
